gen id=.

replace id=99902   if countryname=="Arab World"|countrycode=="ARB"
replace id=99903   if countryname=="Central Europe and the Baltics"|countrycode=="CEB"
replace id=99904   if countryname=="Caribbean small states"|countrycode=="CSS"
replace id=99905   if countryname=="Curacao"|countrycode=="CUW"
replace id=99906   if countryname=="European Union"|countrycode=="EUU"
replace id=99907   if countryname=="Fragile and conflict affected situations"|countrycode=="FCS"
replace id=99908   if countryname=="Not classified"|countrycode=="INX"
replace id=99909   if countryname=="St. Martin (French part)"|countrycode=="MAF"
replace id=99910   if countryname=="OECD members"|countrycode=="OED"
replace id=99911   if countryname=="Other small states"|countrycode=="OSS"
replace id=99912   if countryname=="Pacific island small states"|countrycode=="PSS"
replace id=99913   if countryname=="South Sudan"|countrycode=="SSD"
replace id=99914   if countryname=="Small states"|countrycode=="SST"
replace id=99915   if countryname=="Sint Maarten (Dutch part)"|countrycode=="SXM"
replace id=99916   if countryname=="Taiwan, China"|countrycode=="TWN"
replace id=99917   if countryname=="Sub-Saharan Africa (developing only)"|countrycode=="SSA"
replace id=99918   if countryname=="Sub-Saharan Africa (all income levels)"|countrycode=="SSF"
replace id=99919   if countryname=="South Sudan"|countrycode=="SSD"
replace id=99920   if countryname=="Africa"|countrycode=="AFR"
replace id=99921   if countryname=="Sub-Saharan Africa excluding South Africa and Nigeria"|countrycode=="XZN"
replace id=99922   if countryname=="North Africa"|countrycode=="NAF"
replace id=99923   if countryname=="Sub-Saharan Africa excluding South Africa"|countrycode=="SXZ"
*
replace id=88801   if countryname=="East Asia & Pacific (developing only)"|countrycode=="EAP"
replace id=88802   if countryname=="East Asia & Pacific (all income levels)"|countrycode=="EAS"
replace id=88803   if countryname=="Europe & Central Asia (developing only)"|countrycode=="ECA"
replace id=88804   if countryname=="Europe & Central Asia (all income levels)"|countrycode=="ECS"
replace id=88805   if countryname=="Euro area"|countrycode=="EUA"
replace id=88806   if countryname=="High income"|countrycode=="HIC"
replace id=88807   if countryname=="Heavily indebted poor countries (HIPC)"|countrycode=="HPC"
replace id=88808   if countryname=="Latin America & Caribbean (developing only)"|countrycode=="LAC"
replace id=88809   if countryname=="Latin America & Caribbean (all income levels)"|countrycode=="LCN"
replace id=88810   if countryname=="Least developed countries: UN classification"|countrycode=="LDC"
replace id=88811   if countryname=="Low income"|countrycode=="LIC"
replace id=88812   if countryname=="Lower middle income"|countrycode=="LMC"
replace id=88813   if countryname=="Low & middle income"|countrycode=="LMY"
replace id=88814   if countryname=="Middle East & North Africa (all income levels)"|countrycode=="MEA"
replace id=88815   if countryname=="Middle income"|countrycode=="MIC"
replace id=88816   if countryname=="Middle East & North Africa (developing only)"|countrycode=="MNA"
replace id=88817   if countryname=="North America"|countrycode=="NAC"
replace id=88818   if countryname=="High income: nonOECD"|countrycode=="NOC"
replace id=88819   if countryname=="High income: OECD"|countrycode=="OEC"
replace id=88820   if countryname=="South Asia"|countrycode=="SAS"
replace id=88821   if countryname=="Sub-Saharan Africa (developing only)"|countrycode=="SSA"
replace id=88822   if countryname=="Sub-Saharan Africa (all income levels)"|countrycode=="SSF"
replace id=88823   if countryname=="Upper middle income"|countrycode=="UMC"
replace id=88824   if countryname=="World"|countrycode=="WLD"
*
replace id=77701  if  countryname=="FRENCH GUIANA"|countrycode=="GUF"
replace id=77702  if  countryname=="WEST BANK AND GAZA"|countrycode=="WBG"
replace id=77703  if  countryname=="TIMOR-LESTE"|countrycode=="TMP"
replace id=77704  if  countryname=="MARTINIQUE"|countrycode=="MTQ"
replace id=77705  if  countryname=="R?UNION"|countrycode=="REU"|countryname=="REUNION"
replace id=77706  if  countryname=="NIUE"|countrycode=="NIU"
replace id=77707  if  countryname=="KOSOVO"|countrycode=="KSV"
replace id=77708  if  countryname=="JERSEY, CHANNEL ISLANDS"|countrycode=="JEY"
replace id=77709  if  countryname=="NETHERLANDS ANTILLES (FORMER)"|countrycode=="ANT"
replace id=77710  if  countryname=="ANGUILLA"|countrycode=="AIA"
replace id=77711  if  countryname=="NAURU"|countrycode=="NRU"
replace id=77712  if  countryname=="COOK ISLANDS"|countrycode=="COK"
replace id=77713  if  countryname=="ANDORRA"|countrycode=="ADO"
*replace id=77714  if  countryname=="CONGO, DEM. REP."|countrycode=="ZAR"


replace id=66601  if countryname=="A5M"|countrycode=="A5M"
replace id=66602  if countryname=="EMU"|countrycode=="EMU"
replace id=66603  if countryname=="EUU"|countrycode=="EUU"
replace id=66604  if countryname=="G20"|countrycode=="G20"
replace id=66605  if countryname=="G4E"|countrycode=="G4E"
replace id=66606  if countryname=="G7B"|countrycode=="G7B"
replace id=66607  if countryname=="G7M"|countrycode=="G7M"
replace id=66608  if countryname=="NOC"|countrycode=="NOC"
replace id=66609  if countryname=="OEU"|countrycode=="OEU"
replace id=66610  if countryname=="ONM"|countrycode=="ONM"
replace id=66611  if countryname=="OTO"|countrycode=="OTO"
replace id=66612  if countryname=="SDR"|countrycode=="SDR"
replace id=66613  if countryname=="WLD"|countrycode=="WLD"
replace id=66614  if countryname=="NAT"|countrycode=="NAT"
replace id=66615  if countryname=="BRC"|countrycode=="BRC"

*
replace id=1   if countryname=="Aruba"|countrycode=="ABW"
replace id=2   if countryname=="Afghanistan"|countrycode=="AFG"
replace id=3   if countryname=="Angola"|countrycode=="AGO"
replace id=4   if countryname=="Albania"|countrycode=="ALB"
replace id=5   if countryname=="Andorra"|countrycode=="AND"
replace id=6   if countryname=="United Arab Emirates"|countrycode=="ARE"
replace id=7   if countryname=="Argentina"|countrycode=="ARG"
replace id=8   if countryname=="Armenia"|countrycode=="ARM"
replace id=9   if countryname=="American Samoa"|countrycode=="ASM"
replace id=10   if countryname=="Antigua and Barbuda"|countrycode=="ATG"
replace id=11   if countryname=="Australia"|countrycode=="AUS"
replace id=12   if countryname=="Austria"|countrycode=="AUT"
replace id=13   if countryname=="Azerbaijan"|countrycode=="AZE"
replace id=14   if countryname=="Burundi"|countrycode=="BDI"
replace id=15   if countryname=="Belgium"|countrycode=="BEL"
replace id=16   if countryname=="Benin"|countrycode=="BEN"
replace id=17   if countryname=="Burkina Faso"|countrycode=="BFA"
replace id=18   if countryname=="Bangladesh"|countrycode=="BGD"
replace id=19   if countryname=="Bulgaria"|countrycode=="BGR"
replace id=20   if countryname=="Bahrain"|countrycode=="BHR"
replace id=21   if countryname=="Bahamas, The"|countrycode=="BHS"
replace id=22   if countryname=="Bosnia and Herzegovina"|countrycode=="BIH"
replace id=23   if countryname=="Belarus"|countrycode=="BLR"
replace id=24   if countryname=="Belize"|countrycode=="BLZ"
replace id=25   if countryname=="Bermuda"|countrycode=="BMU"
replace id=26   if countryname=="Bolivia"|countrycode=="BOL"
replace id=27   if countryname=="Brazil"|countrycode=="BRA"
replace id=28   if countryname=="Barbados"|countrycode=="BRB"
replace id=29   if countryname=="Brunei Darussalam"|countrycode=="BRN"
replace id=30   if countryname=="Bhutan"|countrycode=="BTN"
replace id=31   if countryname=="Botswana"|countrycode=="BWA"
replace id=32   if countryname=="Central African Republic"|countrycode=="CAF"
replace id=33   if countryname=="Canada"|countrycode=="CAN"
replace id=34   if countryname=="Switzerland"|countrycode=="CHE"
replace id=35   if countryname=="Channel Islands"|countrycode=="CHI"
replace id=36   if countryname=="Chile"|countrycode=="CHL"
replace id=37   if countryname=="China"|countrycode=="CHN"
replace id=38   if countryname=="Cote d'Ivoire"|countrycode=="CIV"
replace id=39   if countryname=="Cameroon"|countrycode=="CMR"
replace id=40   if countryname=="COD, Dem. Rep."|countrycode=="COD"|countryname=="CONGO, DEM. REP."
replace id=41   if countryname=="Congo, Rep."|countrycode=="COG"
replace id=42   if countryname=="Colombia"|countrycode=="COL"
replace id=43   if countryname=="Comoros"|countrycode=="COM"
replace id=44   if countryname=="Cabo Verde"|countrycode=="CPV"
replace id=45   if countryname=="Costa Rica"|countrycode=="CRI"
replace id=46   if countryname=="Cuba"|countrycode=="CUB"
replace id=47   if countryname=="Cayman Islands"|countrycode=="CYM"
replace id=48   if countryname=="Cyprus"|countrycode=="CYP"
replace id=49   if countryname=="Czech Republic"|countrycode=="CZE"
replace id=50   if countryname=="Germany"|countrycode=="DEU"
replace id=51   if countryname=="Djibouti"|countrycode=="DJI"
replace id=52   if countryname=="Dominica"|countrycode=="DMA"
replace id=53   if countryname=="Denmark"|countrycode=="DNK"
replace id=54   if countryname=="Dominican Republic"|countrycode=="DOM"
replace id=55   if countryname=="Algeria"|countrycode=="DZA"
replace id=56   if countryname=="Ecuador"|countrycode=="ECU"
replace id=57   if countryname=="Egypt, Arab Rep."|countrycode=="EGY"
replace id=58   if countryname=="Eritrea"|countrycode=="ERI"
replace id=59   if countryname=="Spain"|countrycode=="ESP"
replace id=60   if countryname=="Estonia"|countrycode=="EST"
replace id=61   if countryname=="Ethiopia"|countrycode=="ETH"
replace id=62   if countryname=="Finland"|countrycode=="FIN"
replace id=63   if countryname=="Fiji"|countrycode=="FJI"
replace id=64   if countryname=="France"|countrycode=="FRA"
replace id=65   if countryname=="Faeroe Islands"|countrycode=="FRO"
replace id=66   if countryname=="Micronesia, Fed. Sts."|countrycode=="FSM"
replace id=67   if countryname=="Gabon"|countrycode=="GAB"
replace id=68   if countryname=="United Kingdom"|countrycode=="GBR"
replace id=69   if countryname=="Georgia"|countrycode=="GEO"
replace id=70   if countryname=="Ghana"|countrycode=="GHA"
replace id=71   if countryname=="Guinea"|countrycode=="GIN"
replace id=72   if countryname=="Gambia, The"|countrycode=="GMB"
replace id=73   if countryname=="Guinea-Bissau"|countrycode=="GNB"
replace id=74   if countryname=="Equatorial Guinea"|countrycode=="GNQ"
replace id=75   if countryname=="Greece"|countrycode=="GRC"
replace id=76   if countryname=="Grenada"|countrycode=="GRD"
replace id=77   if countryname=="Greenland"|countrycode=="GRL"
replace id=78   if countryname=="Guatemala"|countrycode=="GTM"
replace id=79   if countryname=="Guam"|countrycode=="GUM"
replace id=80   if countryname=="Guyana"|countrycode=="GUY"
replace id=81   if countryname=="Hong Kong SAR, China"|countrycode=="HKG"
replace id=82   if countryname=="Honduras"|countrycode=="HND"
replace id=83   if countryname=="Croatia"|countrycode=="HRV"
replace id=84   if countryname=="Haiti"|countrycode=="HTI"
replace id=85   if countryname=="Hungary"|countrycode=="HUN"
replace id=86   if countryname=="Indonesia"|countrycode=="IDN"
replace id=87   if countryname=="Isle of Man"|countrycode=="IMN"
replace id=88   if countryname=="India"|countrycode=="IND"
replace id=89   if countryname=="Ireland"|countrycode=="IRL"
replace id=90   if countryname=="Iran, Islamic Rep."|countrycode=="IRN"
replace id=91   if countryname=="Iraq"|countrycode=="IRQ"
replace id=92   if countryname=="Iceland"|countrycode=="ISL"
replace id=93   if countryname=="Israel"|countrycode=="ISR"
replace id=94   if countryname=="Italy"|countrycode=="ITA"
replace id=95   if countryname=="Jamaica"|countrycode=="JAM"
replace id=96   if countryname=="Jordan"|countrycode=="JOR"
replace id=97   if countryname=="Japan"|countrycode=="JPN"
replace id=98   if countryname=="Kazakhstan"|countrycode=="KAZ"
replace id=99   if countryname=="Kenya"|countrycode=="KEN"
replace id=100   if countryname=="Kyrgyz Republic"|countrycode=="KGZ"
replace id=101   if countryname=="Cambodia"|countrycode=="KHM"
replace id=102   if countryname=="Kiribati"|countrycode=="KIR"
replace id=103   if countryname=="St. Kitts and Nevis"|countrycode=="KNA"
replace id=104   if countryname=="Korea, Rep."|countrycode=="KOR"
replace id=105   if countryname=="Kuwait"|countrycode=="KWT"
replace id=106   if countryname=="Lao PDR"|countrycode=="LAO"
replace id=107   if countryname=="Lebanon"|countrycode=="LBN"
replace id=108   if countryname=="Liberia"|countrycode=="LBR"
replace id=109   if countryname=="Libya"|countrycode=="LBY"
replace id=110   if countryname=="St. Lucia"|countrycode=="LCA"
replace id=111   if countryname=="Liechtenstein"|countrycode=="LIE"
replace id=112   if countryname=="Sri Lanka"|countrycode=="LKA"
replace id=113   if countryname=="Lesotho"|countrycode=="LSO"
replace id=114   if countryname=="Lithuania"|countrycode=="LTU"
replace id=115   if countryname=="Luxembourg"|countrycode=="LUX"
replace id=116   if countryname=="Latvia"|countrycode=="LVA"
replace id=117   if countryname=="Macao SAR, China"|countrycode=="MAC"
replace id=118   if countryname=="Morocco"|countrycode=="MAR"
replace id=119   if countryname=="Monaco"|countrycode=="MCO"
replace id=120   if countryname=="Moldova"|countrycode=="MDA"
replace id=121   if countryname=="Madagascar"|countrycode=="MDG"
replace id=122   if countryname=="Maldives"|countrycode=="MDV"
replace id=123   if countryname=="Mexico"|countrycode=="MEX"
replace id=124   if countryname=="Marshall Islands"|countrycode=="MHL"
replace id=125   if countryname=="Macedonia, FYR"|countrycode=="MKD"
replace id=126   if countryname=="Mali"|countrycode=="MLI"
replace id=127   if countryname=="Malta"|countrycode=="MLT"
replace id=128   if countryname=="Myanmar"|countrycode=="MMR"
replace id=129   if countryname=="Montenegro"|countrycode=="MNE"
replace id=130   if countryname=="Mongolia"|countrycode=="MNG"
replace id=131   if countryname=="Northern Mariana Islands"|countrycode=="MNP"
replace id=132   if countryname=="Mozambique"|countrycode=="MOZ"
replace id=133   if countryname=="Mauritania"|countrycode=="MRT"
replace id=134   if countryname=="Mauritius"|countrycode=="MUS"
replace id=135   if countryname=="Malawi"|countrycode=="MWI"
replace id=136   if countryname=="Malaysia"|countrycode=="MYS"
replace id=137   if countryname=="Namibia"|countrycode=="NAM"
replace id=138   if countryname=="New Caledonia"|countrycode=="NCL"
replace id=139   if countryname=="Niger"|countrycode=="NER"
replace id=140   if countryname=="Nigeria"|countrycode=="NGA"
replace id=141   if countryname=="Nicaragua"|countrycode=="NIC"
replace id=142   if countryname=="Netherlands"|countrycode=="NLD"
replace id=143   if countryname=="Norway"|countrycode=="NOR"
replace id=144   if countryname=="Nepal"|countrycode=="NPL"
replace id=145   if countryname=="New Zealand"|countrycode=="NZL"
replace id=146   if countryname=="Oman"|countrycode=="OMN"
replace id=147   if countryname=="Pakistan"|countrycode=="PAK"
replace id=148   if countryname=="Panama"|countrycode=="PAN"
replace id=149   if countryname=="Peru"|countrycode=="PER"
replace id=150   if countryname=="Philippines"|countrycode=="PHL"
replace id=151   if countryname=="Palau"|countrycode=="PLW"
replace id=152   if countryname=="Papua New Guinea"|countrycode=="PNG"
replace id=153   if countryname=="Poland"|countrycode=="POL"
replace id=154   if countryname=="Puerto Rico"|countrycode=="PRI"
replace id=155   if countryname=="Korea, Dem. Rep."|countrycode=="PRK"
replace id=156   if countryname=="Portugal"|countrycode=="PRT"
replace id=157   if countryname=="Paraguay"|countrycode=="PRY"
replace id=158   if countryname=="West Bank and Gaza"|countrycode=="PSE"
replace id=159   if countryname=="French Polynesia"|countrycode=="PYF"
replace id=160   if countryname=="Qatar"|countrycode=="QAT"
***
replace id=161   if countryname=="Romania"|countrycode=="ROU"|countrycode=="ROM"
replace id=162   if countryname=="Russian Federation"|countrycode=="RUS"
replace id=163   if countryname=="Rwanda"|countrycode=="RWA"
replace id=164   if countryname=="Saudi Arabia"|countrycode=="SAU"
replace id=165   if countryname=="Sudan"|countrycode=="SDN"
replace id=166   if countryname=="Senegal"|countrycode=="SEN"
replace id=167   if countryname=="Singapore"|countrycode=="SGP"
replace id=168   if countryname=="Solomon Islands"|countrycode=="SLB"
replace id=169   if countryname=="Sierra Leone"|countrycode=="SLE"
replace id=170   if countryname=="El Salvador"|countrycode=="SLV"
replace id=171   if countryname=="San Marino"|countrycode=="SMR"
replace id=172   if countryname=="Somalia"|countrycode=="SOM"
replace id=173   if countryname=="Serbia"|countrycode=="SRB"
replace id=174   if countryname=="Sao Tome and Principe"|countrycode=="STP"
replace id=175   if countryname=="Suriname"|countrycode=="SUR"
replace id=176   if countryname=="Slovak Republic"|countrycode=="SVK"
replace id=177   if countryname=="Slovenia"|countrycode=="SVN"
replace id=178   if countryname=="Sweden"|countrycode=="SWE"
replace id=179   if countryname=="Swaziland"|countrycode=="SWZ"
replace id=180   if countryname=="Seychelles"|countrycode=="SYC"
replace id=181   if countryname=="Syrian Arab Republic"|countrycode=="SYR"
replace id=182   if countryname=="Turks and Caicos Islands"|countrycode=="TCA"
replace id=183   if countryname=="Chad"|countrycode=="TCD"
replace id=184   if countryname=="Togo"|countrycode=="TGO"
replace id=185   if countryname=="Thailand"|countrycode=="THA"
replace id=186   if countryname=="Tajikistan"|countrycode=="TJK"
replace id=187   if countryname=="Turkmenistan"|countrycode=="TKM"
replace id=188   if countryname=="Timor-Leste"|countrycode=="TLS"
replace id=189   if countryname=="Tonga"|countrycode=="TON"
replace id=190   if countryname=="Trinidad and Tobago"|countrycode=="TTO"
replace id=191   if countryname=="Tunisia"|countrycode=="TUN"
replace id=192   if countryname=="Turkey"|countrycode=="TUR"
replace id=193   if countryname=="Tuvalu"|countrycode=="TUV"
replace id=194   if countryname=="Tanzania"|countrycode=="TZA"
replace id=195   if countryname=="Uganda"|countrycode=="UGA"
replace id=196   if countryname=="Ukraine"|countrycode=="UKR"
replace id=197   if countryname=="Uruguay"|countrycode=="URY"
replace id=198   if countryname=="United States"|countrycode=="USA"
replace id=199   if countryname=="Uzbekistan"|countrycode=="UZB"
replace id=200   if countryname=="St. Vincent and the Grenadines"|countrycode=="VCT"
replace id=201   if countryname=="Venezuela, RB"|countrycode=="VEN"
replace id=202   if countryname=="Virgin Islands (U.S.)"|countrycode=="VIR"
replace id=203   if countryname=="Vietnam"|countrycode=="VNM"
replace id=204   if countryname=="Vanuatu"|countrycode=="VUT"
replace id=205   if countryname=="Samoa"|countrycode=="WSM"
replace id=206   if countryname=="Yemen, Rep."|countrycode=="YEM"
replace id=207   if countryname=="South Africa"|countrycode=="ZAF"
replace id=208   if countryname=="Zambia"|countrycode=="ZMB"
replace id=209   if countryname=="Zimbabwe"|countrycode=="ZWE"


